name: perfcli
description: PerfCli is a basic command-line application written in dart to test the response time of a backend URL
version: 1.0.0
author: Apparence.io
homepage: https://github.com/g-apparence/perfcli

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  args: ^2.0.0
  path: ^1.8.0
  http: ^0.13.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
